// Objective-C API for talking to github.com/NYU-Efficient-Room-Traversal/Rangefinder Go package.
//   gobind -lang=objc github.com/NYU-Efficient-Room-Traversal/Rangefinder
//
// File is generated by gobind. Do not edit.

#ifndef __Rangefinder_H__
#define __Rangefinder_H__

@import Foundation;
#include "Universe.objc.h"


@class RangefinderImageMatrix;
@class RangefinderMonoImageMatrix;
@class RangefinderPixel;

@interface RangefinderImageMatrix : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
@end

@interface RangefinderMonoImageMatrix : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
@end

@interface RangefinderPixel : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
@end

// skipped function Calibrate with unsupported parameter or return types


FOUNDATION_EXPORT double RangefinderGetLaserDistance(double angle, double triangleBase);

// skipped function GetLaserOffset with unsupported parameter or return types


FOUNDATION_EXPORT RangefinderImageMatrix* RangefinderNewImageMatrix(long width, long height);

FOUNDATION_EXPORT RangefinderMonoImageMatrix* RangefinderNewMonoImageMatrix(long width, long height);

#endif
