
// Objective-C API for talking to the following Go packages
//
//	github.com/NYU-Efficient-Room-Traversal/Rangefinder
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Rangefinder_FRAMEWORK_H__
#define __Rangefinder_FRAMEWORK_H__

#include "Rangefinder.objc.h"
#include "Universe.objc.h"

#endif
